### ISSUE TITLE
Authentication to tum shibboleth not working

### ISSUE THREAD

**Issue by LadnerJonas** [omareldeeb/tum-moodle-downloader#4]
I think tum made changes to the auth server. Thus, the authentication in `authentication.py` is not possible. I tried some things here and there, but i do not have the needed knowledge to fix the code. 

```bash
> python src/main.py download 
  
Starting Moodle session...
Traceback (most recent call last):
  File "/home/ladner/Downloads/Moodle-Downloader/src/main.py", line 57, in <module>
    session = authentication.start_session(
  File "/home/ladner/Downloads/Moodle-Downloader/src/authentication.py", line 54, in start_session
    action_url = _find_action_url(soup)
  File "/home/ladner/Downloads/Moodle-Downloader/src/authentication.py", line 21, in _find_action_url
    form = content_div.find('form')
AttributeError: 'NoneType' object has no attribute `'find'`
```

**Comment by LadnerJonas** [comment]
This fork seems to work.
https://github.com/code-byter/tum-moodle-downloader
